# ---------------------------------------------------------------------
# @author Filip Kocica (xkocic01@stud.fit.vutbr.cz)
# @date 2/22/2020
# @brief FLP project - Makefile
# ---------------------------------------------------------------------
FN=simplify-bkg.hs

all:
	ghc --make $(FN)

test: all
	./test.sh

clean:
	rm *.hi *.o